version: '3.8'

# Development overrides for docker-compose.yml
services:
  redis:
    ports:
      - "6379:6379"  # Expose Redis port for development

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
      target: development  # Could add a dev stage to Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CORS_ORIGIN=http://localhost:5173
    ports:
      - "3000:3000"  # Expose backend port for development

  frontend:
    build:
      context: ./client
      dockerfile: ../Dockerfile.frontend
      target: development
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - "5173:5173"  # Expose frontend dev server
    command: npm run dev
